image:
  file: .gitpod.Dockerfile

tasks:
  - before: mkdir -p /workspace/data
    command: |
      mongod --dbpath /workspace/data

  - name: Apostrophe init
    before: apos create app
    command: |
      apos create app
      gp sync-done app      

  - name: Install node-modules
    init: gp sync-await app
    command: |
      cd ${GITPOD_REPO_ROOT}/app && npm install
      gp sync-done node-modules

  - name: DEV SHELL
    init: gp sync-await node-modules
    command: cd ${GITPOD_REPO_ROOT}/app && npm run dev
    

ports:
  - port: 3000
    onOpen: open-preview      

vscode:
  extensions:
    - eamodio.gitlens
    - akosyakov.gitpod-monitor
    - redhat.vscode-yaml
